
disabled_rules:
#- empty_parameters
#- empty_parentheses_with_trailing_closure
#- generic_type_name
#- identifier_name
#- implicit_getter
#- inert_defer
#- is_disjoint
#- leading_whitespace
#- legacy_cggeometry_functions
#- legacy_constant
#- legacy_constructor
#- legacy_hashing
#- legacy_nsgeometry_functions
#- nesting
#- no_fallthrough_only
#- no_space_in_method_call
#- notification_center_detachment
#- nsobject_prefer_isequal
#- operator_whitespace
#- orphaned_doc_comment
#- private_unit_test
#- protocol_property_accessors_order
#- redundant_discardable_let
#- redundant_objc_attribute
#- redundant_optional_initialization
#- redundant_set_access_control
#- redundant_void_return
#- return_arrow_whitespace
#- shorthand_operator
#- statement_position
#- superfluous_disable_command
#- switch_case_alignment
#- syntactic_sugar
#- todo
#- trailing_comma
#- trailing_semicolon
#- type_name
#- unneeded_break_in_switch
#- unused_capture_list
#- unused_control_flow_label
#- unused_enumerated
#- unused_optional_binding
#- unused_setter_value
#- valid_ibinspectable
#- vertical_parameter_alignment
#- weak_delegate
#- xctfail_message
#- empty_enum_arguments

opt_in_rules:
- empty_count
- force_unwrapping
- legacy_constant
- legacy_constructor
- private_action
- private_outlet
- unused_capture_list
- unused_control_flow_label
- unused_enumerated
- unused_optional_binding
- unused_setter_value
- valid_ibinspectable
- vertical_parameter_alignment
- weak_delegate
- xctfail_message
- empty_enum_arguments
- trailing_comma
- trailing_semicolon
- type_name
- unneeded_break_in_switch
- statement_position
- superfluous_disable_command
- switch_case_alignment
- syntactic_sugar
- empty_parameters
- empty_parentheses_with_trailing_closure
- generic_type_name
- identifier_name
- implicit_getter
- inert_defer
- is_disjoint
- leading_whitespace
- legacy_cggeometry_functions
- legacy_constant
- legacy_constructor
- legacy_hashing
- legacy_nsgeometry_functions
- nesting
- no_fallthrough_only
- no_space_in_method_call
- notification_center_detachment
- nsobject_prefer_isequal
- operator_whitespace
- orphaned_doc_comment
- private_unit_test
- protocol_property_accessors_order
- redundant_discardable_let
- redundant_objc_attribute
- redundant_optional_initialization
- redundant_set_access_control
- redundant_void_return
- return_arrow_whitespace
- shorthand_operator
- todo

excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib

force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level

type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly

file_length:
    - 1000 # warning
    - 1000 # error
ignore_comment_only_lines: true

line_length:
- 120 # warning
- 250 # error

function_body_length:
- 100 # warning
- 100 # error

function_parameter_count:
- 5 # warning
- 8 # error

cyclomatic_complexity:
- 10 # warning
- 15 # error

large_tuple:
- 10 # warning
- 20 # error

reporter: "xcode"

